version: '3.8'

services:
  # Golang Backend (Arion)
  backend:
    build:
      context: ./arion
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=recapo_user
      - DB_PASSWORD=Recapo123!
      - DB_NAME=recapo_master
    depends_on:
      - postgres
    networks:
      - recapo-network

  # Next.js Frontend (Oncius)
  frontend:
    build:
      context: ./oncius
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - recapo-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=recapo_master
      - POSTGRES_USER=recapo_user
      - POSTGRES_PASSWORD=Recapo123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recapo-network

volumes:
  postgres_data:

networks:
  recapo-network:
    driver: bridge
