FROM prom/prometheus:v2.51.0

COPY prometheus.prod.yml /etc/prometheus/prometheus.template.yml

USER root
RUN apk add --no-cache coreutils

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
