// Code generated by MockGen. DO NOT EDIT.
// Source: store/customer.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/zeirash/recapo/arion/model"
	store "github.com/zeirash/recapo/arion/store"
)

// MockCustomerStore is a mock of CustomerStore interface.
type MockCustomerStore struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerStoreMockRecorder
}

// MockCustomerStoreMockRecorder is the mock recorder for MockCustomerStore.
type MockCustomerStoreMockRecorder struct {
	mock *MockCustomerStore
}

// NewMockCustomerStore creates a new mock instance.
func NewMockCustomerStore(ctrl *gomock.Controller) *MockCustomerStore {
	mock := &MockCustomerStore{ctrl: ctrl}
	mock.recorder = &MockCustomerStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerStore) EXPECT() *MockCustomerStoreMockRecorder {
	return m.recorder
}

// CreateCustomer mocks base method.
func (m *MockCustomerStore) CreateCustomer(name, phone, address string, shopID int) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", name, phone, address, shopID)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockCustomerStoreMockRecorder) CreateCustomer(name, phone, address, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockCustomerStore)(nil).CreateCustomer), name, phone, address, shopID)
}

// DeleteCustomerByID mocks base method.
func (m *MockCustomerStore) DeleteCustomerByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomerByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomerByID indicates an expected call of DeleteCustomerByID.
func (mr *MockCustomerStoreMockRecorder) DeleteCustomerByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomerByID", reflect.TypeOf((*MockCustomerStore)(nil).DeleteCustomerByID), id)
}

// GetCustomerByID mocks base method.
func (m *MockCustomerStore) GetCustomerByID(id int, shopID ...int) (*model.Customer, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{id}
	for _, a := range shopID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCustomerByID", varargs...)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID.
func (mr *MockCustomerStoreMockRecorder) GetCustomerByID(id interface{}, shopID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id}, shopID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockCustomerStore)(nil).GetCustomerByID), varargs...)
}

// GetCustomersByShopID mocks base method.
func (m *MockCustomerStore) GetCustomersByShopID(shopID int) ([]model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersByShopID", shopID)
	ret0, _ := ret[0].([]model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomersByShopID indicates an expected call of GetCustomersByShopID.
func (mr *MockCustomerStoreMockRecorder) GetCustomersByShopID(shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersByShopID", reflect.TypeOf((*MockCustomerStore)(nil).GetCustomersByShopID), shopID)
}

// UpdateCustomer mocks base method.
func (m *MockCustomerStore) UpdateCustomer(id int, input store.UpdateCustomerInput) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomer", id, input)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomer indicates an expected call of UpdateCustomer.
func (mr *MockCustomerStoreMockRecorder) UpdateCustomer(id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockCustomerStore)(nil).UpdateCustomer), id, input)
}
