// Code generated by MockGen. DO NOT EDIT.
// Source: store/invitation.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/zeirash/recapo/arion/model"
)

// MockInvitationStore is a mock of InvitationStore interface.
type MockInvitationStore struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationStoreMockRecorder
}

// MockInvitationStoreMockRecorder is the mock recorder for MockInvitationStore.
type MockInvitationStoreMockRecorder struct {
	mock *MockInvitationStore
}

// NewMockInvitationStore creates a new mock instance.
func NewMockInvitationStore(ctrl *gomock.Controller) *MockInvitationStore {
	mock := &MockInvitationStore{ctrl: ctrl}
	mock.recorder = &MockInvitationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationStore) EXPECT() *MockInvitationStoreMockRecorder {
	return m.recorder
}

// CreateInvitation mocks base method.
func (m *MockInvitationStore) CreateInvitation(ctx context.Context, shopID, invitedBy int, email, token string) (*model.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", ctx, shopID, invitedBy, email, token)
	ret0, _ := ret[0].(*model.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockInvitationStoreMockRecorder) CreateInvitation(ctx, shopID, invitedBy, email, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockInvitationStore)(nil).CreateInvitation), ctx, shopID, invitedBy, email, token)
}

// GetInvitationByToken mocks base method.
func (m *MockInvitationStore) GetInvitationByToken(ctx context.Context, token string) (*model.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvitationByToken", ctx, token)
	ret0, _ := ret[0].(*model.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvitationByToken indicates an expected call of GetInvitationByToken.
func (mr *MockInvitationStoreMockRecorder) GetInvitationByToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvitationByToken", reflect.TypeOf((*MockInvitationStore)(nil).GetInvitationByToken), ctx, token)
}

// GetPendingInvitationByEmail mocks base method.
func (m *MockInvitationStore) GetPendingInvitationByEmail(ctx context.Context, shopID int, email string) (*model.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingInvitationByEmail", ctx, shopID, email)
	ret0, _ := ret[0].(*model.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingInvitationByEmail indicates an expected call of GetPendingInvitationByEmail.
func (mr *MockInvitationStoreMockRecorder) GetPendingInvitationByEmail(ctx, shopID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingInvitationByEmail", reflect.TypeOf((*MockInvitationStore)(nil).GetPendingInvitationByEmail), ctx, shopID, email)
}

// AcceptInvitation mocks base method.
func (m *MockInvitationStore) AcceptInvitation(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvitation", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptInvitation indicates an expected call of AcceptInvitation.
func (mr *MockInvitationStoreMockRecorder) AcceptInvitation(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvitation", reflect.TypeOf((*MockInvitationStore)(nil).AcceptInvitation), ctx, id)
}
