// Code generated by MockGen. DO NOT EDIT.
// Source: store/order_item.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	database "github.com/zeirash/recapo/arion/common/database"
	model "github.com/zeirash/recapo/arion/model"
	store "github.com/zeirash/recapo/arion/store"
)

// MockOrderItemStore is a mock of OrderItemStore interface.
type MockOrderItemStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrderItemStoreMockRecorder
}

// MockOrderItemStoreMockRecorder is the mock recorder for MockOrderItemStore.
type MockOrderItemStoreMockRecorder struct {
	mock *MockOrderItemStore
}

// NewMockOrderItemStore creates a new mock instance.
func NewMockOrderItemStore(ctrl *gomock.Controller) *MockOrderItemStore {
	mock := &MockOrderItemStore{ctrl: ctrl}
	mock.recorder = &MockOrderItemStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderItemStore) EXPECT() *MockOrderItemStoreMockRecorder {
	return m.recorder
}

// CreateOrderItem mocks base method.
func (m *MockOrderItemStore) CreateOrderItem(ctx context.Context, tx database.Tx, orderID, productID, qty int) (*model.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItem", ctx, tx, orderID, productID, qty)
	ret0, _ := ret[0].(*model.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderItem indicates an expected call of CreateOrderItem.
func (mr *MockOrderItemStoreMockRecorder) CreateOrderItem(ctx, tx, orderID, productID, qty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItem", reflect.TypeOf((*MockOrderItemStore)(nil).CreateOrderItem), ctx, tx, orderID, productID, qty)
}

// CreateTempOrderItem mocks base method.
func (m *MockOrderItemStore) CreateTempOrderItem(ctx context.Context, tx database.Tx, tempOrderID, productID, qty int) (*model.TempOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTempOrderItem", ctx, tx, tempOrderID, productID, qty)
	ret0, _ := ret[0].(*model.TempOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTempOrderItem indicates an expected call of CreateTempOrderItem.
func (mr *MockOrderItemStoreMockRecorder) CreateTempOrderItem(ctx, tx, tempOrderID, productID, qty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTempOrderItem", reflect.TypeOf((*MockOrderItemStore)(nil).CreateTempOrderItem), ctx, tx, tempOrderID, productID, qty)
}

// DeleteOrderItemByID mocks base method.
func (m *MockOrderItemStore) DeleteOrderItemByID(ctx context.Context, id, orderID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderItemByID", ctx, id, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderItemByID indicates an expected call of DeleteOrderItemByID.
func (mr *MockOrderItemStoreMockRecorder) DeleteOrderItemByID(ctx, id, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderItemByID", reflect.TypeOf((*MockOrderItemStore)(nil).DeleteOrderItemByID), ctx, id, orderID)
}

// DeleteOrderItemsByOrderID mocks base method.
func (m *MockOrderItemStore) DeleteOrderItemsByOrderID(ctx context.Context, tx database.Tx, orderID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderItemsByOrderID", ctx, tx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderItemsByOrderID indicates an expected call of DeleteOrderItemsByOrderID.
func (mr *MockOrderItemStoreMockRecorder) DeleteOrderItemsByOrderID(ctx, tx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderItemsByOrderID", reflect.TypeOf((*MockOrderItemStore)(nil).DeleteOrderItemsByOrderID), ctx, tx, orderID)
}

// DeleteOrderItemsByProductID mocks base method.
func (m *MockOrderItemStore) DeleteOrderItemsByProductID(ctx context.Context, tx database.Tx, productID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderItemsByProductID", ctx, tx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderItemsByProductID indicates an expected call of DeleteOrderItemsByProductID.
func (mr *MockOrderItemStoreMockRecorder) DeleteOrderItemsByProductID(ctx, tx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderItemsByProductID", reflect.TypeOf((*MockOrderItemStore)(nil).DeleteOrderItemsByProductID), ctx, tx, productID)
}

// GetNetSalesByShopID mocks base method.
func (m *MockOrderItemStore) GetNetSalesByShopID(ctx context.Context, shopID int, opts model.OrderFilterOptions) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetSalesByShopID", ctx, shopID, opts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetSalesByShopID indicates an expected call of GetNetSalesByShopID.
func (mr *MockOrderItemStoreMockRecorder) GetNetSalesByShopID(ctx, shopID, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetSalesByShopID", reflect.TypeOf((*MockOrderItemStore)(nil).GetNetSalesByShopID), ctx, shopID, opts)
}

// GetOrderTotalsExcludingProduct mocks base method.
func (m *MockOrderItemStore) GetOrderTotalsExcludingProduct(ctx context.Context, productID int) (map[int]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderTotalsExcludingProduct", ctx, productID)
	ret0, _ := ret[0].(map[int]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderTotalsExcludingProduct indicates an expected call of GetOrderTotalsExcludingProduct.
func (mr *MockOrderItemStoreMockRecorder) GetOrderTotalsExcludingProduct(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderTotalsExcludingProduct", reflect.TypeOf((*MockOrderItemStore)(nil).GetOrderTotalsExcludingProduct), ctx, productID)
}

// GetOrderItemByID mocks base method.
func (m *MockOrderItemStore) GetOrderItemByID(ctx context.Context, id int) (*model.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItemByID", ctx, id)
	ret0, _ := ret[0].(*model.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItemByID indicates an expected call of GetOrderItemByID.
func (mr *MockOrderItemStoreMockRecorder) GetOrderItemByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItemByID", reflect.TypeOf((*MockOrderItemStore)(nil).GetOrderItemByID), ctx, id)
}

// GetOrderItemByProductID mocks base method.
func (m *MockOrderItemStore) GetOrderItemByProductID(ctx context.Context, productID, orderID int) (*model.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItemByProductID", ctx, productID, orderID)
	ret0, _ := ret[0].(*model.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItemByProductID indicates an expected call of GetOrderItemByProductID.
func (mr *MockOrderItemStoreMockRecorder) GetOrderItemByProductID(ctx, productID, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItemByProductID", reflect.TypeOf((*MockOrderItemStore)(nil).GetOrderItemByProductID), ctx, productID, orderID)
}

// GetOrderItemsByOrderID mocks base method.
func (m *MockOrderItemStore) GetOrderItemsByOrderID(ctx context.Context, orderID int) ([]model.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItemsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]model.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItemsByOrderID indicates an expected call of GetOrderItemsByOrderID.
func (mr *MockOrderItemStoreMockRecorder) GetOrderItemsByOrderID(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItemsByOrderID", reflect.TypeOf((*MockOrderItemStore)(nil).GetOrderItemsByOrderID), ctx, orderID)
}

// GetTempOrderItemsByTempOrderID mocks base method.
func (m *MockOrderItemStore) GetTempOrderItemsByTempOrderID(ctx context.Context, tempOrderID int) ([]model.TempOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTempOrderItemsByTempOrderID", ctx, tempOrderID)
	ret0, _ := ret[0].([]model.TempOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTempOrderItemsByTempOrderID indicates an expected call of GetTempOrderItemsByTempOrderID.
func (mr *MockOrderItemStoreMockRecorder) GetTempOrderItemsByTempOrderID(ctx, tempOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTempOrderItemsByTempOrderID", reflect.TypeOf((*MockOrderItemStore)(nil).GetTempOrderItemsByTempOrderID), ctx, tempOrderID)
}

// UpdateOrderItemByID mocks base method.
func (m *MockOrderItemStore) UpdateOrderItemByID(ctx context.Context, tx database.Tx, id, orderID int, input store.UpdateOrderItemInput) (*model.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderItemByID", ctx, tx, id, orderID, input)
	ret0, _ := ret[0].(*model.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderItemByID indicates an expected call of UpdateOrderItemByID.
func (mr *MockOrderItemStoreMockRecorder) UpdateOrderItemByID(ctx, tx, id, orderID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderItemByID", reflect.TypeOf((*MockOrderItemStore)(nil).UpdateOrderItemByID), ctx, tx, id, orderID, input)
}
