// Code generated by MockGen. DO NOT EDIT.
// Source: store/order_item.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	database "github.com/zeirash/recapo/arion/common/database"
	model "github.com/zeirash/recapo/arion/model"
	store "github.com/zeirash/recapo/arion/store"
)

// MockOrderItemStore is a mock of OrderItemStore interface.
type MockOrderItemStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrderItemStoreMockRecorder
}

// MockOrderItemStoreMockRecorder is the mock recorder for MockOrderItemStore.
type MockOrderItemStoreMockRecorder struct {
	mock *MockOrderItemStore
}

// NewMockOrderItemStore creates a new mock instance.
func NewMockOrderItemStore(ctrl *gomock.Controller) *MockOrderItemStore {
	mock := &MockOrderItemStore{ctrl: ctrl}
	mock.recorder = &MockOrderItemStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderItemStore) EXPECT() *MockOrderItemStoreMockRecorder {
	return m.recorder
}

// CreateOrderItem mocks base method.
func (m *MockOrderItemStore) CreateOrderItem(orderID, productID, qty int) (*model.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItem", orderID, productID, qty)
	ret0, _ := ret[0].(*model.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderItem indicates an expected call of CreateOrderItem.
func (mr *MockOrderItemStoreMockRecorder) CreateOrderItem(orderID, productID, qty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItem", reflect.TypeOf((*MockOrderItemStore)(nil).CreateOrderItem), orderID, productID, qty)
}

// CreateOrderItemTemp mocks base method.
func (m *MockOrderItemStore) CreateOrderItemTemp(tx database.Tx, orderTempID, productID, qty int) (*model.OrderTempItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItemTemp", tx, orderTempID, productID, qty)
	ret0, _ := ret[0].(*model.OrderTempItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderItemTemp indicates an expected call of CreateOrderItemTemp.
func (mr *MockOrderItemStoreMockRecorder) CreateOrderItemTemp(tx, orderTempID, productID, qty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItemTemp", reflect.TypeOf((*MockOrderItemStore)(nil).CreateOrderItemTemp), tx, orderTempID, productID, qty)
}

// DeleteOrderItemByID mocks base method.
func (m *MockOrderItemStore) DeleteOrderItemByID(id, orderID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderItemByID", id, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderItemByID indicates an expected call of DeleteOrderItemByID.
func (mr *MockOrderItemStoreMockRecorder) DeleteOrderItemByID(id, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderItemByID", reflect.TypeOf((*MockOrderItemStore)(nil).DeleteOrderItemByID), id, orderID)
}

// DeleteOrderItemsByOrderID mocks base method.
func (m *MockOrderItemStore) DeleteOrderItemsByOrderID(tx database.Tx, orderID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderItemsByOrderID", tx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderItemsByOrderID indicates an expected call of DeleteOrderItemsByOrderID.
func (mr *MockOrderItemStoreMockRecorder) DeleteOrderItemsByOrderID(tx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderItemsByOrderID", reflect.TypeOf((*MockOrderItemStore)(nil).DeleteOrderItemsByOrderID), tx, orderID)
}

// GetOrderItemByID mocks base method.
func (m *MockOrderItemStore) GetOrderItemByID(id int) (*model.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItemByID", id)
	ret0, _ := ret[0].(*model.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItemByID indicates an expected call of GetOrderItemByID.
func (mr *MockOrderItemStoreMockRecorder) GetOrderItemByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItemByID", reflect.TypeOf((*MockOrderItemStore)(nil).GetOrderItemByID), id)
}

// GetOrderItemsByOrderID mocks base method.
func (m *MockOrderItemStore) GetOrderItemsByOrderID(orderID int) ([]model.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItemsByOrderID", orderID)
	ret0, _ := ret[0].([]model.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItemsByOrderID indicates an expected call of GetOrderItemsByOrderID.
func (mr *MockOrderItemStoreMockRecorder) GetOrderItemsByOrderID(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItemsByOrderID", reflect.TypeOf((*MockOrderItemStore)(nil).GetOrderItemsByOrderID), orderID)
}

// UpdateOrderItemByID mocks base method.
func (m *MockOrderItemStore) UpdateOrderItemByID(id, orderID int, input store.UpdateOrderItemInput) (*model.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderItemByID", id, orderID, input)
	ret0, _ := ret[0].(*model.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderItemByID indicates an expected call of UpdateOrderItemByID.
func (mr *MockOrderItemStoreMockRecorder) UpdateOrderItemByID(id, orderID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderItemByID", reflect.TypeOf((*MockOrderItemStore)(nil).UpdateOrderItemByID), id, orderID, input)
}
