// Code generated by MockGen. DO NOT EDIT.
// Source: store/order.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	database "github.com/zeirash/recapo/arion/common/database"
	model "github.com/zeirash/recapo/arion/model"
	store "github.com/zeirash/recapo/arion/store"
)

// MockOrderStore is a mock of OrderStore interface.
type MockOrderStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStoreMockRecorder
}

// MockOrderStoreMockRecorder is the mock recorder for MockOrderStore.
type MockOrderStoreMockRecorder struct {
	mock *MockOrderStore
}

// NewMockOrderStore creates a new mock instance.
func NewMockOrderStore(ctrl *gomock.Controller) *MockOrderStore {
	mock := &MockOrderStore{ctrl: ctrl}
	mock.recorder = &MockOrderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStore) EXPECT() *MockOrderStoreMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderStore) CreateOrder(customerID, shopID int, notes *string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", customerID, shopID, notes)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderStoreMockRecorder) CreateOrder(customerID, shopID, notes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderStore)(nil).CreateOrder), customerID, shopID, notes)
}

// CreateTempOrder mocks base method.
func (m *MockOrderStore) CreateTempOrder(tx database.Tx, customerName, customerPhone string, shopID int) (*model.TempOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTempOrder", tx, customerName, customerPhone, shopID)
	ret0, _ := ret[0].(*model.TempOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTempOrder indicates an expected call of CreateTempOrder.
func (mr *MockOrderStoreMockRecorder) CreateTempOrder(tx, customerName, customerPhone, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTempOrder", reflect.TypeOf((*MockOrderStore)(nil).CreateTempOrder), tx, customerName, customerPhone, shopID)
}

// DeleteOrderByID mocks base method.
func (m *MockOrderStore) DeleteOrderByID(tx database.Tx, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderByID", tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderByID indicates an expected call of DeleteOrderByID.
func (mr *MockOrderStoreMockRecorder) DeleteOrderByID(tx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderByID", reflect.TypeOf((*MockOrderStore)(nil).DeleteOrderByID), tx, id)
}

// GetOrderByID mocks base method.
func (m *MockOrderStore) GetOrderByID(id int, shopID ...int) (*model.Order, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{id}
	for _, a := range shopID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrderByID", varargs...)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderStoreMockRecorder) GetOrderByID(id interface{}, shopID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id}, shopID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderStore)(nil).GetOrderByID), varargs...)
}

// GetOrdersByShopID mocks base method.
func (m *MockOrderStore) GetOrdersByShopID(shopID int, opts model.OrderFilterOptions) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByShopID", shopID, opts)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByShopID indicates an expected call of GetOrdersByShopID.
func (mr *MockOrderStoreMockRecorder) GetOrdersByShopID(shopID, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByShopID", reflect.TypeOf((*MockOrderStore)(nil).GetOrdersByShopID), shopID, opts)
}

// GetTempOrderByID mocks base method.
func (m *MockOrderStore) GetTempOrderByID(id int, shopID ...int) (*model.TempOrder, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{id}
	for _, a := range shopID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTempOrderByID", varargs...)
	ret0, _ := ret[0].(*model.TempOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTempOrderByID indicates an expected call of GetTempOrderByID.
func (mr *MockOrderStoreMockRecorder) GetTempOrderByID(id interface{}, shopID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id}, shopID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTempOrderByID", reflect.TypeOf((*MockOrderStore)(nil).GetTempOrderByID), varargs...)
}

// GetTempOrdersByShopID mocks base method.
func (m *MockOrderStore) GetTempOrdersByShopID(shopID int, opts model.OrderFilterOptions) ([]model.TempOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTempOrdersByShopID", shopID, opts)
	ret0, _ := ret[0].([]model.TempOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTempOrdersByShopID indicates an expected call of GetTempOrdersByShopID.
func (mr *MockOrderStoreMockRecorder) GetTempOrdersByShopID(shopID, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTempOrdersByShopID", reflect.TypeOf((*MockOrderStore)(nil).GetTempOrdersByShopID), shopID, opts)
}

// HasActiveOrdersByCustomerID mocks base method.
func (m *MockOrderStore) HasActiveOrdersByCustomerID(customerID, shopID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveOrdersByCustomerID", customerID, shopID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasActiveOrdersByCustomerID indicates an expected call of HasActiveOrdersByCustomerID.
func (mr *MockOrderStoreMockRecorder) HasActiveOrdersByCustomerID(customerID, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveOrdersByCustomerID", reflect.TypeOf((*MockOrderStore)(nil).HasActiveOrdersByCustomerID), customerID, shopID)
}

// UpdateOrder mocks base method.
func (m *MockOrderStore) UpdateOrder(id int, input store.UpdateOrderInput) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", id, input)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockOrderStoreMockRecorder) UpdateOrder(id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockOrderStore)(nil).UpdateOrder), id, input)
}

// UpdateTempOrderTotalPrice mocks base method.
func (m *MockOrderStore) UpdateTempOrderTotalPrice(tx database.Tx, tempOrderID, totalPrice int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTempOrderTotalPrice", tx, tempOrderID, totalPrice)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTempOrderTotalPrice indicates an expected call of UpdateTempOrderTotalPrice.
func (mr *MockOrderStoreMockRecorder) UpdateTempOrderTotalPrice(tx, tempOrderID, totalPrice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTempOrderTotalPrice", reflect.TypeOf((*MockOrderStore)(nil).UpdateTempOrderTotalPrice), tx, tempOrderID, totalPrice)
}
