// Code generated by MockGen. DO NOT EDIT.
// Source: store/product.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/zeirash/recapo/arion/model"
	store "github.com/zeirash/recapo/arion/store"
)

// MockProductStore is a mock of ProductStore interface.
type MockProductStore struct {
	ctrl     *gomock.Controller
	recorder *MockProductStoreMockRecorder
}

// MockProductStoreMockRecorder is the mock recorder for MockProductStore.
type MockProductStoreMockRecorder struct {
	mock *MockProductStore
}

// NewMockProductStore creates a new mock instance.
func NewMockProductStore(ctrl *gomock.Controller) *MockProductStore {
	mock := &MockProductStore{ctrl: ctrl}
	mock.recorder = &MockProductStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductStore) EXPECT() *MockProductStoreMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductStore) CreateProduct(name string, description *string, price, shopID int, originalPrice *int) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", name, description, price, shopID, originalPrice)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductStoreMockRecorder) CreateProduct(name, description, price, shopID, originalPrice interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductStore)(nil).CreateProduct), name, description, price, shopID, originalPrice)
}

// DeleteProductByID mocks base method.
func (m *MockProductStore) DeleteProductByID(productID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductByID", productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductByID indicates an expected call of DeleteProductByID.
func (mr *MockProductStoreMockRecorder) DeleteProductByID(productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductByID", reflect.TypeOf((*MockProductStore)(nil).DeleteProductByID), productID)
}

// GetProductByID mocks base method.
func (m *MockProductStore) GetProductByID(productID int, shopID ...int) (*model.Product, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{productID}
	for _, a := range shopID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProductByID", varargs...)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductStoreMockRecorder) GetProductByID(productID interface{}, shopID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{productID}, shopID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductStore)(nil).GetProductByID), varargs...)
}

// GetProductsByShopID mocks base method.
func (m *MockProductStore) GetProductsByShopID(shopID int, searchQuery *string) ([]model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByShopID", shopID, searchQuery)
	ret0, _ := ret[0].([]model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByShopID indicates an expected call of GetProductsByShopID.
func (mr *MockProductStoreMockRecorder) GetProductsByShopID(shopID, searchQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByShopID", reflect.TypeOf((*MockProductStore)(nil).GetProductsByShopID), shopID, searchQuery)
}

// GetProductsListByActiveOrders mocks base method.
func (m *MockProductStore) GetProductsListByActiveOrders(shopID int) ([]model.PurchaseProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsListByActiveOrders", shopID)
	ret0, _ := ret[0].([]model.PurchaseProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsListByActiveOrders indicates an expected call of GetProductsListByActiveOrders.
func (mr *MockProductStoreMockRecorder) GetProductsListByActiveOrders(shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsListByActiveOrders", reflect.TypeOf((*MockProductStore)(nil).GetProductsListByActiveOrders), shopID)
}

// UpdateProduct mocks base method.
func (m *MockProductStore) UpdateProduct(productID int, input store.UpdateProductInput) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", productID, input)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductStoreMockRecorder) UpdateProduct(productID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductStore)(nil).UpdateProduct), productID, input)
}
