// Code generated by MockGen. DO NOT EDIT.
// Source: store/shop.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	database "github.com/zeirash/recapo/arion/common/database"
	model "github.com/zeirash/recapo/arion/model"
)

// MockShopStore is a mock of ShopStore interface.
type MockShopStore struct {
	ctrl     *gomock.Controller
	recorder *MockShopStoreMockRecorder
}

// MockShopStoreMockRecorder is the mock recorder for MockShopStore.
type MockShopStoreMockRecorder struct {
	mock *MockShopStore
}

// NewMockShopStore creates a new mock instance.
func NewMockShopStore(ctrl *gomock.Controller) *MockShopStore {
	mock := &MockShopStore{ctrl: ctrl}
	mock.recorder = &MockShopStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopStore) EXPECT() *MockShopStoreMockRecorder {
	return m.recorder
}

// CreateShop mocks base method.
func (m *MockShopStore) CreateShop(tx database.Tx, name string) (*model.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShop", tx, name)
	ret0, _ := ret[0].(*model.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShop indicates an expected call of CreateShop.
func (mr *MockShopStoreMockRecorder) CreateShop(tx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShop", reflect.TypeOf((*MockShopStore)(nil).CreateShop), tx, name)
}
