// Code generated by MockGen. DO NOT EDIT.
// Source: store/system.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	store "github.com/zeirash/recapo/arion/store"
)

// MockSystemStore is a mock of SystemStore interface.
type MockSystemStore struct {
	ctrl     *gomock.Controller
	recorder *MockSystemStoreMockRecorder
}

// MockSystemStoreMockRecorder is the mock recorder for MockSystemStore.
type MockSystemStoreMockRecorder struct {
	mock *MockSystemStore
}

// NewMockSystemStore creates a new mock instance.
func NewMockSystemStore(ctrl *gomock.Controller) *MockSystemStore {
	mock := &MockSystemStore{ctrl: ctrl}
	mock.recorder = &MockSystemStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemStore) EXPECT() *MockSystemStoreMockRecorder {
	return m.recorder
}

// GetSystemStats mocks base method.
func (m *MockSystemStore) GetSystemStats(ctx context.Context) (*store.SystemStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemStats", ctx)
	ret0, _ := ret[0].(*store.SystemStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemStats indicates an expected call of GetSystemStats.
func (mr *MockSystemStoreMockRecorder) GetSystemStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemStats", reflect.TypeOf((*MockSystemStore)(nil).GetSystemStats), ctx)
}

// GetSystemShops mocks base method.
func (m *MockSystemStore) GetSystemShops(ctx context.Context) ([]store.SystemShop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemShops", ctx)
	ret0, _ := ret[0].([]store.SystemShop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemShops indicates an expected call of GetSystemShops.
func (mr *MockSystemStoreMockRecorder) GetSystemShops(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemShops", reflect.TypeOf((*MockSystemStore)(nil).GetSystemShops), ctx)
}

// GetSystemPayments mocks base method.
func (m *MockSystemStore) GetSystemPayments(ctx context.Context) ([]store.SystemPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemPayments", ctx)
	ret0, _ := ret[0].([]store.SystemPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemPayments indicates an expected call of GetSystemPayments.
func (mr *MockSystemStoreMockRecorder) GetSystemPayments(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemPayments", reflect.TypeOf((*MockSystemStore)(nil).GetSystemPayments), ctx)
}
