// Code generated by MockGen. DO NOT EDIT.
// Source: store/token.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/zeirash/recapo/arion/model"
)

// MockTokenStore is a mock of TokenStore interface.
type MockTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockTokenStoreMockRecorder
}

// MockTokenStoreMockRecorder is the mock recorder for MockTokenStore.
type MockTokenStoreMockRecorder struct {
	mock *MockTokenStore
}

// NewMockTokenStore creates a new mock instance.
func NewMockTokenStore(ctrl *gomock.Controller) *MockTokenStore {
	mock := &MockTokenStore{ctrl: ctrl}
	mock.recorder = &MockTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenStore) EXPECT() *MockTokenStoreMockRecorder {
	return m.recorder
}

// CreateAccessToken mocks base method.
func (m *MockTokenStore) CreateAccessToken(ctx context.Context, user *model.User, secret string, expiry int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessToken", ctx, user, secret, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessToken indicates an expected call of CreateAccessToken.
func (mr *MockTokenStoreMockRecorder) CreateAccessToken(ctx, user, secret, expiry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessToken", reflect.TypeOf((*MockTokenStore)(nil).CreateAccessToken), ctx, user, secret, expiry)
}

// CreateRefreshToken mocks base method.
func (m *MockTokenStore) CreateRefreshToken(ctx context.Context, user *model.User, secret string, expiry int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, user, secret, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockTokenStoreMockRecorder) CreateRefreshToken(ctx, user, secret, expiry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockTokenStore)(nil).CreateRefreshToken), ctx, user, secret, expiry)
}

// ExtractDataFromToken mocks base method.
func (m *MockTokenStore) ExtractDataFromToken(ctx context.Context, requestToken, secret string) (model.TokenData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractDataFromToken", ctx, requestToken, secret)
	ret0, _ := ret[0].(model.TokenData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractDataFromToken indicates an expected call of ExtractDataFromToken.
func (mr *MockTokenStoreMockRecorder) ExtractDataFromToken(ctx, requestToken, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractDataFromToken", reflect.TypeOf((*MockTokenStore)(nil).ExtractDataFromToken), ctx, requestToken, secret)
}

// IsAuthorized mocks base method.
func (m *MockTokenStore) IsAuthorized(ctx context.Context, requestToken, secret string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorized", ctx, requestToken, secret)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAuthorized indicates an expected call of IsAuthorized.
func (mr *MockTokenStoreMockRecorder) IsAuthorized(ctx, requestToken, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorized", reflect.TypeOf((*MockTokenStore)(nil).IsAuthorized), ctx, requestToken, secret)
}
