// Code generated by MockGen. DO NOT EDIT.
// Source: arion/store/user.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	database "github.com/zeirash/recapo/arion/common/database"
	model "github.com/zeirash/recapo/arion/model"
	store "github.com/zeirash/recapo/arion/store"
)

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// ClearSessionToken mocks base method.
func (m *MockUserStore) ClearSessionToken(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSessionToken", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSessionToken indicates an expected call of ClearSessionToken.
func (mr *MockUserStoreMockRecorder) ClearSessionToken(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSessionToken", reflect.TypeOf((*MockUserStore)(nil).ClearSessionToken), ctx, userID)
}

// CountUsersByShopID mocks base method.
func (m *MockUserStore) CountUsersByShopID(ctx context.Context, shopID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsersByShopID", ctx, shopID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsersByShopID indicates an expected call of CountUsersByShopID.
func (mr *MockUserStoreMockRecorder) CountUsersByShopID(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsersByShopID", reflect.TypeOf((*MockUserStore)(nil).CountUsersByShopID), ctx, shopID)
}

// CreateUser mocks base method.
func (m *MockUserStore) CreateUser(ctx context.Context, tx database.Tx, name, email, hashPassword, role string, shop_id int) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, tx, name, email, hashPassword, role, shop_id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserStoreMockRecorder) CreateUser(ctx, tx, name, email, hashPassword, role, shop_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserStore)(nil).CreateUser), ctx, tx, name, email, hashPassword, role, shop_id)
}

// GetOwnerByShopID mocks base method.
func (m *MockUserStore) GetOwnerByShopID(ctx context.Context, shopID int) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnerByShopID", ctx, shopID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnerByShopID indicates an expected call of GetOwnerByShopID.
func (mr *MockUserStoreMockRecorder) GetOwnerByShopID(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnerByShopID", reflect.TypeOf((*MockUserStore)(nil).GetOwnerByShopID), ctx, shopID)
}

// GetUserByEmail mocks base method.
func (m *MockUserStore) GetUserByEmail(ctx context.Context, email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserStoreMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserStore)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserStore) GetUserByID(ctx context.Context, userID int) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserStoreMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserStore)(nil).GetUserByID), ctx, userID)
}

// GetUsers mocks base method.
func (m *MockUserStore) GetUsers(ctx context.Context) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockUserStoreMockRecorder) GetUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockUserStore)(nil).GetUsers), ctx)
}

// GetUsersByShopID mocks base method.
func (m *MockUserStore) GetUsersByShopID(ctx context.Context, shopID int) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByShopID", ctx, shopID)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByShopID indicates an expected call of GetUsersByShopID.
func (mr *MockUserStoreMockRecorder) GetUsersByShopID(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByShopID", reflect.TypeOf((*MockUserStore)(nil).GetUsersByShopID), ctx, shopID)
}

// IsValidRole mocks base method.
func (m *MockUserStore) IsValidRole(role string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidRole", role)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValidRole indicates an expected call of IsValidRole.
func (mr *MockUserStoreMockRecorder) IsValidRole(role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidRole", reflect.TypeOf((*MockUserStore)(nil).IsValidRole), role)
}

// Roles mocks base method.
func (m *MockUserStore) Roles() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Roles")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Roles indicates an expected call of Roles.
func (mr *MockUserStoreMockRecorder) Roles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Roles", reflect.TypeOf((*MockUserStore)(nil).Roles))
}

// SetSessionToken mocks base method.
func (m *MockUserStore) SetSessionToken(ctx context.Context, userID int, sessionToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionToken", ctx, userID, sessionToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionToken indicates an expected call of SetSessionToken.
func (mr *MockUserStoreMockRecorder) SetSessionToken(ctx, userID, sessionToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionToken", reflect.TypeOf((*MockUserStore)(nil).SetSessionToken), ctx, userID, sessionToken)
}

// UpdateUser mocks base method.
func (m *MockUserStore) UpdateUser(ctx context.Context, id int, input store.UpdateUserInput) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, input)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserStoreMockRecorder) UpdateUser(ctx, id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserStore)(nil).UpdateUser), ctx, id, input)
}
