// Code generated by MockGen. DO NOT EDIT.
// Source: service/customer.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/zeirash/recapo/arion/common/response"
	service "github.com/zeirash/recapo/arion/service"
)

// MockCustomerService is a mock of CustomerService interface.
type MockCustomerService struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerServiceMockRecorder
}

// MockCustomerServiceMockRecorder is the mock recorder for MockCustomerService.
type MockCustomerServiceMockRecorder struct {
	mock *MockCustomerService
}

// NewMockCustomerService creates a new mock instance.
func NewMockCustomerService(ctrl *gomock.Controller) *MockCustomerService {
	mock := &MockCustomerService{ctrl: ctrl}
	mock.recorder = &MockCustomerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerService) EXPECT() *MockCustomerServiceMockRecorder {
	return m.recorder
}

// CreateCustomer mocks base method.
func (m *MockCustomerService) CreateCustomer(name, email, password string, shopID int) (response.CustomerData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", name, email, password, shopID)
	ret0, _ := ret[0].(response.CustomerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockCustomerServiceMockRecorder) CreateCustomer(name, email, password, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockCustomerService)(nil).CreateCustomer), name, email, password, shopID)
}

// DeleteCustomerByID mocks base method.
func (m *MockCustomerService) DeleteCustomerByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomerByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomerByID indicates an expected call of DeleteCustomerByID.
func (mr *MockCustomerServiceMockRecorder) DeleteCustomerByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomerByID", reflect.TypeOf((*MockCustomerService)(nil).DeleteCustomerByID), id)
}

// GetCustomerByID mocks base method.
func (m *MockCustomerService) GetCustomerByID(customerID int, shopID ...int) (*response.CustomerData, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{customerID}
	for _, a := range shopID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCustomerByID", varargs...)
	ret0, _ := ret[0].(*response.CustomerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID.
func (mr *MockCustomerServiceMockRecorder) GetCustomerByID(customerID interface{}, shopID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{customerID}, shopID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockCustomerService)(nil).GetCustomerByID), varargs...)
}

// GetCustomersByShopID mocks base method.
func (m *MockCustomerService) GetCustomersByShopID(shopID int, searchQuery *string) ([]response.CustomerData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersByShopID", shopID, searchQuery)
	ret0, _ := ret[0].([]response.CustomerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomersByShopID indicates an expected call of GetCustomersByShopID.
func (mr *MockCustomerServiceMockRecorder) GetCustomersByShopID(shopID, searchQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersByShopID", reflect.TypeOf((*MockCustomerService)(nil).GetCustomersByShopID), shopID, searchQuery)
}

// HasActiveOrders mocks base method.
func (m *MockCustomerService) HasActiveOrders(customerID, shopID int) (response.CustomerHasActiveOrdersData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveOrders", customerID, shopID)
	ret0, _ := ret[0].(response.CustomerHasActiveOrdersData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasActiveOrders indicates an expected call of HasActiveOrders.
func (mr *MockCustomerServiceMockRecorder) HasActiveOrders(customerID, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveOrders", reflect.TypeOf((*MockCustomerService)(nil).HasActiveOrders), customerID, shopID)
}

// UpdateCustomer mocks base method.
func (m *MockCustomerService) UpdateCustomer(input service.UpdateCustomerInput) (response.CustomerData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomer", input)
	ret0, _ := ret[0].(response.CustomerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCustomer indicates an expected call of UpdateCustomer.
func (mr *MockCustomerServiceMockRecorder) UpdateCustomer(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockCustomerService)(nil).UpdateCustomer), input)
}
