// Code generated by MockGen. DO NOT EDIT.
// Source: service/invitation.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/zeirash/recapo/arion/common/response"
)

// MockInvitationService is a mock of InvitationService interface.
type MockInvitationService struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationServiceMockRecorder
}

// MockInvitationServiceMockRecorder is the mock recorder for MockInvitationService.
type MockInvitationServiceMockRecorder struct {
	mock *MockInvitationService
}

// NewMockInvitationService creates a new mock instance.
func NewMockInvitationService(ctrl *gomock.Controller) *MockInvitationService {
	mock := &MockInvitationService{ctrl: ctrl}
	mock.recorder = &MockInvitationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationService) EXPECT() *MockInvitationServiceMockRecorder {
	return m.recorder
}

// InviteAdmin mocks base method.
func (m *MockInvitationService) InviteAdmin(ctx context.Context, shopID, userID int, email, lang string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteAdmin", ctx, shopID, userID, email, lang)
	ret0, _ := ret[0].(error)
	return ret0
}

// InviteAdmin indicates an expected call of InviteAdmin.
func (mr *MockInvitationServiceMockRecorder) InviteAdmin(ctx, shopID, userID, email, lang interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteAdmin", reflect.TypeOf((*MockInvitationService)(nil).InviteAdmin), ctx, shopID, userID, email, lang)
}

// ValidateInviteToken mocks base method.
func (m *MockInvitationService) ValidateInviteToken(ctx context.Context, token string) (*response.InvitationData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateInviteToken", ctx, token)
	ret0, _ := ret[0].(*response.InvitationData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateInviteToken indicates an expected call of ValidateInviteToken.
func (mr *MockInvitationServiceMockRecorder) ValidateInviteToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateInviteToken", reflect.TypeOf((*MockInvitationService)(nil).ValidateInviteToken), ctx, token)
}

// AcceptInvite mocks base method.
func (m *MockInvitationService) AcceptInvite(ctx context.Context, token, name, password string) (response.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvite", ctx, token, name, password)
	ret0, _ := ret[0].(response.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptInvite indicates an expected call of AcceptInvite.
func (mr *MockInvitationServiceMockRecorder) AcceptInvite(ctx, token, name, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvite", reflect.TypeOf((*MockInvitationService)(nil).AcceptInvite), ctx, token, name, password)
}
