// Code generated by MockGen. DO NOT EDIT.
// Source: service/order.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/zeirash/recapo/arion/common/response"
	model "github.com/zeirash/recapo/arion/model"
	service "github.com/zeirash/recapo/arion/service"
)

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderService) CreateOrder(customerID, shopID int, notes *string) (response.OrderData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", customerID, shopID, notes)
	ret0, _ := ret[0].(response.OrderData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderServiceMockRecorder) CreateOrder(customerID, shopID, notes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderService)(nil).CreateOrder), customerID, shopID, notes)
}

// CreateOrderItem mocks base method.
func (m *MockOrderService) CreateOrderItem(orderID, productID, qty int) (response.OrderItemData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItem", orderID, productID, qty)
	ret0, _ := ret[0].(response.OrderItemData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderItem indicates an expected call of CreateOrderItem.
func (mr *MockOrderServiceMockRecorder) CreateOrderItem(orderID, productID, qty interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItem", reflect.TypeOf((*MockOrderService)(nil).CreateOrderItem), orderID, productID, qty)
}

// CreateOrderTemp mocks base method.
func (m *MockOrderService) CreateOrderTemp(customerName, customerPhone, shareToken string, items []service.CreateOrderTempItemInput) (response.OrderTempData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderTemp", customerName, customerPhone, shareToken, items)
	ret0, _ := ret[0].(response.OrderTempData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderTemp indicates an expected call of CreateOrderTemp.
func (mr *MockOrderServiceMockRecorder) CreateOrderTemp(customerName, customerPhone, shareToken, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderTemp", reflect.TypeOf((*MockOrderService)(nil).CreateOrderTemp), customerName, customerPhone, shareToken, items)
}

// DeleteOrderByID mocks base method.
func (m *MockOrderService) DeleteOrderByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderByID indicates an expected call of DeleteOrderByID.
func (mr *MockOrderServiceMockRecorder) DeleteOrderByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderByID", reflect.TypeOf((*MockOrderService)(nil).DeleteOrderByID), id)
}

// DeleteOrderItemByID mocks base method.
func (m *MockOrderService) DeleteOrderItemByID(orderItemID, orderID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrderItemByID", orderItemID, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrderItemByID indicates an expected call of DeleteOrderItemByID.
func (mr *MockOrderServiceMockRecorder) DeleteOrderItemByID(orderItemID, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrderItemByID", reflect.TypeOf((*MockOrderService)(nil).DeleteOrderItemByID), orderItemID, orderID)
}

// GetOrderByID mocks base method.
func (m *MockOrderService) GetOrderByID(id int, shopID ...int) (*response.OrderData, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{id}
	for _, a := range shopID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrderByID", varargs...)
	ret0, _ := ret[0].(*response.OrderData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderServiceMockRecorder) GetOrderByID(id interface{}, shopID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{id}, shopID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderService)(nil).GetOrderByID), varargs...)
}

// GetOrderItemByID mocks base method.
func (m *MockOrderService) GetOrderItemByID(orderItemID, orderID int) (response.OrderItemData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItemByID", orderItemID, orderID)
	ret0, _ := ret[0].(response.OrderItemData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItemByID indicates an expected call of GetOrderItemByID.
func (mr *MockOrderServiceMockRecorder) GetOrderItemByID(orderItemID, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItemByID", reflect.TypeOf((*MockOrderService)(nil).GetOrderItemByID), orderItemID, orderID)
}

// GetOrderItemsByOrderID mocks base method.
func (m *MockOrderService) GetOrderItemsByOrderID(orderID int) ([]response.OrderItemData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItemsByOrderID", orderID)
	ret0, _ := ret[0].([]response.OrderItemData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItemsByOrderID indicates an expected call of GetOrderItemsByOrderID.
func (mr *MockOrderServiceMockRecorder) GetOrderItemsByOrderID(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItemsByOrderID", reflect.TypeOf((*MockOrderService)(nil).GetOrderItemsByOrderID), orderID)
}

// GetOrdersByShopID mocks base method.
func (m *MockOrderService) GetOrdersByShopID(shopID int, opts model.OrderFilterOptions) ([]response.OrderData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByShopID", shopID, opts)
	ret0, _ := ret[0].([]response.OrderData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByShopID indicates an expected call of GetOrdersByShopID.
func (mr *MockOrderServiceMockRecorder) GetOrdersByShopID(shopID, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByShopID", reflect.TypeOf((*MockOrderService)(nil).GetOrdersByShopID), shopID, opts)
}

// UpdateOrderByID mocks base method.
func (m *MockOrderService) UpdateOrderByID(input service.UpdateOrderInput) (response.OrderData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderByID", input)
	ret0, _ := ret[0].(response.OrderData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderByID indicates an expected call of UpdateOrderByID.
func (mr *MockOrderServiceMockRecorder) UpdateOrderByID(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderByID", reflect.TypeOf((*MockOrderService)(nil).UpdateOrderByID), input)
}

// UpdateOrderItemByID mocks base method.
func (m *MockOrderService) UpdateOrderItemByID(input service.UpdateOrderItemInput) (response.OrderItemData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderItemByID", input)
	ret0, _ := ret[0].(response.OrderItemData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderItemByID indicates an expected call of UpdateOrderItemByID.
func (mr *MockOrderServiceMockRecorder) UpdateOrderItemByID(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderItemByID", reflect.TypeOf((*MockOrderService)(nil).UpdateOrderItemByID), input)
}
