// Code generated by MockGen. DO NOT EDIT.
// Source: service/product.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/zeirash/recapo/arion/common/response"
	model "github.com/zeirash/recapo/arion/model"
	service "github.com/zeirash/recapo/arion/service"
)

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// ActivateAllProductsByShopID mocks base method.
func (m *MockProductService) ActivateAllProductsByShopID(ctx context.Context, shopID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateAllProductsByShopID", ctx, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateAllProductsByShopID indicates an expected call of ActivateAllProductsByShopID.
func (mr *MockProductServiceMockRecorder) ActivateAllProductsByShopID(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateAllProductsByShopID", reflect.TypeOf((*MockProductService)(nil).ActivateAllProductsByShopID), ctx, shopID)
}

// CreateProduct mocks base method.
func (m *MockProductService) CreateProduct(ctx context.Context, shopID int, name string, description *string, price int, originalPrice *int, imageURL *string) (response.ProductData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, shopID, name, description, price, originalPrice, imageURL)
	ret0, _ := ret[0].(response.ProductData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductServiceMockRecorder) CreateProduct(ctx, shopID, name, description, price, originalPrice, imageURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductService)(nil).CreateProduct), ctx, shopID, name, description, price, originalPrice, imageURL)
}

// DeactivateAllProductsByShopID mocks base method.
func (m *MockProductService) DeactivateAllProductsByShopID(ctx context.Context, shopID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateAllProductsByShopID", ctx, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateAllProductsByShopID indicates an expected call of DeactivateAllProductsByShopID.
func (mr *MockProductServiceMockRecorder) DeactivateAllProductsByShopID(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateAllProductsByShopID", reflect.TypeOf((*MockProductService)(nil).DeactivateAllProductsByShopID), ctx, shopID)
}

// DeleteProductByID mocks base method.
func (m *MockProductService) DeleteProductByID(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductByID indicates an expected call of DeleteProductByID.
func (mr *MockProductServiceMockRecorder) DeleteProductByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductByID", reflect.TypeOf((*MockProductService)(nil).DeleteProductByID), ctx, id)
}

// DeleteProductImage mocks base method.
func (m *MockProductService) DeleteProductImage(ctx context.Context, imageURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductImage", ctx, imageURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductImage indicates an expected call of DeleteProductImage.
func (mr *MockProductServiceMockRecorder) DeleteProductImage(ctx, imageURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductImage", reflect.TypeOf((*MockProductService)(nil).DeleteProductImage), ctx, imageURL)
}

// GetProductByID mocks base method.
func (m *MockProductService) GetProductByID(ctx context.Context, productID int, shopID ...int) (*response.ProductData, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, productID}
	for _, a := range shopID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProductByID", varargs...)
	ret0, _ := ret[0].(*response.ProductData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductServiceMockRecorder) GetProductByID(ctx, productID interface{}, shopID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, productID}, shopID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductService)(nil).GetProductByID), varargs...)
}

// GetProductsByShopID mocks base method.
func (m *MockProductService) GetProductsByShopID(ctx context.Context, shopID int, filter model.FilterOptions) ([]response.ProductData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByShopID", ctx, shopID, filter)
	ret0, _ := ret[0].([]response.ProductData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByShopID indicates an expected call of GetProductsByShopID.
func (mr *MockProductServiceMockRecorder) GetProductsByShopID(ctx, shopID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByShopID", reflect.TypeOf((*MockProductService)(nil).GetProductsByShopID), ctx, shopID, filter)
}

// GetPurchaseListProducts mocks base method.
func (m *MockProductService) GetPurchaseListProducts(ctx context.Context, shopID int) ([]response.PurchaseListProductData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseListProducts", ctx, shopID)
	ret0, _ := ret[0].([]response.PurchaseListProductData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseListProducts indicates an expected call of GetPurchaseListProducts.
func (mr *MockProductServiceMockRecorder) GetPurchaseListProducts(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseListProducts", reflect.TypeOf((*MockProductService)(nil).GetPurchaseListProducts), ctx, shopID)
}

// UpdateProduct mocks base method.
func (m *MockProductService) UpdateProduct(ctx context.Context, input service.UpdateProductInput) (response.ProductData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, input)
	ret0, _ := ret[0].(response.ProductData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductServiceMockRecorder) UpdateProduct(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductService)(nil).UpdateProduct), ctx, input)
}

// UploadProductImage mocks base method.
func (m *MockProductService) UploadProductImage(ctx context.Context, file io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadProductImage", ctx, file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadProductImage indicates an expected call of UploadProductImage.
func (mr *MockProductServiceMockRecorder) UploadProductImage(ctx, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadProductImage", reflect.TypeOf((*MockProductService)(nil).UploadProductImage), ctx, file)
}
