// Code generated by MockGen. DO NOT EDIT.
// Source: service/shop.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/zeirash/recapo/arion/common/response"
)

// MockShopService is a mock of ShopService interface.
type MockShopService struct {
	ctrl     *gomock.Controller
	recorder *MockShopServiceMockRecorder
}

// MockShopServiceMockRecorder is the mock recorder for MockShopService.
type MockShopServiceMockRecorder struct {
	mock *MockShopService
}

// NewMockShopService creates a new mock instance.
func NewMockShopService(ctrl *gomock.Controller) *MockShopService {
	mock := &MockShopService{ctrl: ctrl}
	mock.recorder = &MockShopServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopService) EXPECT() *MockShopServiceMockRecorder {
	return m.recorder
}

// GetPublicProducts mocks base method.
func (m *MockShopService) GetPublicProducts(shareToken string) ([]response.ProductData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicProducts", shareToken)
	ret0, _ := ret[0].([]response.ProductData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicProducts indicates an expected call of GetPublicProducts.
func (mr *MockShopServiceMockRecorder) GetPublicProducts(shareToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicProducts", reflect.TypeOf((*MockShopService)(nil).GetPublicProducts), shareToken)
}
