// Code generated by MockGen. DO NOT EDIT.
// Source: service/shop.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/zeirash/recapo/arion/common/response"
)

// MockShopService is a mock of ShopService interface.
type MockShopService struct {
	ctrl     *gomock.Controller
	recorder *MockShopServiceMockRecorder
}

// MockShopServiceMockRecorder is the mock recorder for MockShopService.
type MockShopServiceMockRecorder struct {
	mock *MockShopService
}

// NewMockShopService creates a new mock instance.
func NewMockShopService(ctrl *gomock.Controller) *MockShopService {
	mock := &MockShopService{ctrl: ctrl}
	mock.recorder = &MockShopServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopService) EXPECT() *MockShopServiceMockRecorder {
	return m.recorder
}

// GetPublicProducts mocks base method.
func (m *MockShopService) GetPublicProducts(ctx context.Context, shareToken string) ([]response.ProductData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicProducts", ctx, shareToken)
	ret0, _ := ret[0].([]response.ProductData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicProducts indicates an expected call of GetPublicProducts.
func (mr *MockShopServiceMockRecorder) GetPublicProducts(ctx, shareToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicProducts", reflect.TypeOf((*MockShopService)(nil).GetPublicProducts), ctx, shareToken)
}

// GetShareTokenByID mocks base method.
func (m *MockShopService) GetShareTokenByID(ctx context.Context, shopID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShareTokenByID", ctx, shopID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShareTokenByID indicates an expected call of GetShareTokenByID.
func (mr *MockShopServiceMockRecorder) GetShareTokenByID(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShareTokenByID", reflect.TypeOf((*MockShopService)(nil).GetShareTokenByID), ctx, shopID)
}
