// Code generated by MockGen. DO NOT EDIT.
// Source: service/subscription.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/zeirash/recapo/arion/common/response"
	service "github.com/zeirash/recapo/arion/service"
)

// MockSubscriptionService is a mock of SubscriptionService interface.
type MockSubscriptionService struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionServiceMockRecorder
}

// MockSubscriptionServiceMockRecorder is the mock recorder for MockSubscriptionService.
type MockSubscriptionServiceMockRecorder struct {
	mock *MockSubscriptionService
}

// NewMockSubscriptionService creates a new mock instance.
func NewMockSubscriptionService(ctrl *gomock.Controller) *MockSubscriptionService {
	mock := &MockSubscriptionService{ctrl: ctrl}
	mock.recorder = &MockSubscriptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionService) EXPECT() *MockSubscriptionServiceMockRecorder {
	return m.recorder
}

// GetActivePlans mocks base method.
func (m *MockSubscriptionService) GetActivePlans() ([]response.PlanData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivePlans")
	ret0, _ := ret[0].([]response.PlanData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivePlans indicates an expected call of GetActivePlans.
func (mr *MockSubscriptionServiceMockRecorder) GetActivePlans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivePlans", reflect.TypeOf((*MockSubscriptionService)(nil).GetActivePlans))
}

// GetSubscriptionByShopID mocks base method.
func (m *MockSubscriptionService) GetSubscriptionByShopID(shopID int) (*response.SubscriptionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByShopID", shopID)
	ret0, _ := ret[0].(*response.SubscriptionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByShopID indicates an expected call of GetSubscriptionByShopID.
func (mr *MockSubscriptionServiceMockRecorder) GetSubscriptionByShopID(shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByShopID", reflect.TypeOf((*MockSubscriptionService)(nil).GetSubscriptionByShopID), shopID)
}

// CreateTrialSubscription mocks base method.
func (m *MockSubscriptionService) CreateTrialSubscription(shopID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrialSubscription", shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTrialSubscription indicates an expected call of CreateTrialSubscription.
func (mr *MockSubscriptionServiceMockRecorder) CreateTrialSubscription(shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrialSubscription", reflect.TypeOf((*MockSubscriptionService)(nil).CreateTrialSubscription), shopID)
}

// Checkout mocks base method.
func (m *MockSubscriptionService) Checkout(shopID, planID int) (*response.CheckoutData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", shopID, planID)
	ret0, _ := ret[0].(*response.CheckoutData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Checkout indicates an expected call of Checkout.
func (mr *MockSubscriptionServiceMockRecorder) Checkout(shopID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockSubscriptionService)(nil).Checkout), shopID, planID)
}

// HandleMidtransWebhook mocks base method.
func (m *MockSubscriptionService) HandleMidtransWebhook(payload service.MidtransWebhookPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMidtransWebhook", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMidtransWebhook indicates an expected call of HandleMidtransWebhook.
func (mr *MockSubscriptionServiceMockRecorder) HandleMidtransWebhook(payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMidtransWebhook", reflect.TypeOf((*MockSubscriptionService)(nil).HandleMidtransWebhook), payload)
}

// IsSubscriptionActive mocks base method.
func (m *MockSubscriptionService) IsSubscriptionActive(shopID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSubscriptionActive", shopID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSubscriptionActive indicates an expected call of IsSubscriptionActive.
func (mr *MockSubscriptionServiceMockRecorder) IsSubscriptionActive(shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSubscriptionActive", reflect.TypeOf((*MockSubscriptionService)(nil).IsSubscriptionActive), shopID)
}

// ExpireSubscriptions mocks base method.
func (m *MockSubscriptionService) ExpireSubscriptions() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireSubscriptions")
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpireSubscriptions indicates an expected call of ExpireSubscriptions.
func (mr *MockSubscriptionServiceMockRecorder) ExpireSubscriptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireSubscriptions", reflect.TypeOf((*MockSubscriptionService)(nil).ExpireSubscriptions))
}

// CancelSubscription mocks base method.
func (m *MockSubscriptionService) CancelSubscription(shopID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSubscription", shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSubscription indicates an expected call of CancelSubscription.
func (mr *MockSubscriptionServiceMockRecorder) CancelSubscription(shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSubscription", reflect.TypeOf((*MockSubscriptionService)(nil).CancelSubscription), shopID)
}
