// Code generated by MockGen. DO NOT EDIT.
// Source: service/subscription.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/zeirash/recapo/arion/common/response"
	service "github.com/zeirash/recapo/arion/service"
)

// MockSubscriptionService is a mock of SubscriptionService interface.
type MockSubscriptionService struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionServiceMockRecorder
}

// MockSubscriptionServiceMockRecorder is the mock recorder for MockSubscriptionService.
type MockSubscriptionServiceMockRecorder struct {
	mock *MockSubscriptionService
}

// NewMockSubscriptionService creates a new mock instance.
func NewMockSubscriptionService(ctrl *gomock.Controller) *MockSubscriptionService {
	mock := &MockSubscriptionService{ctrl: ctrl}
	mock.recorder = &MockSubscriptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionService) EXPECT() *MockSubscriptionServiceMockRecorder {
	return m.recorder
}

// GetActivePlans mocks base method.
func (m *MockSubscriptionService) GetActivePlans(ctx context.Context) ([]response.PlanData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivePlans", ctx)
	ret0, _ := ret[0].([]response.PlanData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivePlans indicates an expected call of GetActivePlans.
func (mr *MockSubscriptionServiceMockRecorder) GetActivePlans(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivePlans", reflect.TypeOf((*MockSubscriptionService)(nil).GetActivePlans), ctx)
}

// GetSubscriptionByShopID mocks base method.
func (m *MockSubscriptionService) GetSubscriptionByShopID(ctx context.Context, shopID int) (*response.SubscriptionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByShopID", ctx, shopID)
	ret0, _ := ret[0].(*response.SubscriptionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByShopID indicates an expected call of GetSubscriptionByShopID.
func (mr *MockSubscriptionServiceMockRecorder) GetSubscriptionByShopID(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByShopID", reflect.TypeOf((*MockSubscriptionService)(nil).GetSubscriptionByShopID), ctx, shopID)
}

// CreateTrialSubscription mocks base method.
func (m *MockSubscriptionService) CreateTrialSubscription(ctx context.Context, shopID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrialSubscription", ctx, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTrialSubscription indicates an expected call of CreateTrialSubscription.
func (mr *MockSubscriptionServiceMockRecorder) CreateTrialSubscription(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrialSubscription", reflect.TypeOf((*MockSubscriptionService)(nil).CreateTrialSubscription), ctx, shopID)
}

// Checkout mocks base method.
func (m *MockSubscriptionService) Checkout(ctx context.Context, shopID, planID int) (*response.CheckoutData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", ctx, shopID, planID)
	ret0, _ := ret[0].(*response.CheckoutData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Checkout indicates an expected call of Checkout.
func (mr *MockSubscriptionServiceMockRecorder) Checkout(ctx, shopID, planID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockSubscriptionService)(nil).Checkout), ctx, shopID, planID)
}

// HandleMidtransWebhook mocks base method.
func (m *MockSubscriptionService) HandleMidtransWebhook(ctx context.Context, payload service.MidtransWebhookPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMidtransWebhook", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMidtransWebhook indicates an expected call of HandleMidtransWebhook.
func (mr *MockSubscriptionServiceMockRecorder) HandleMidtransWebhook(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMidtransWebhook", reflect.TypeOf((*MockSubscriptionService)(nil).HandleMidtransWebhook), ctx, payload)
}

// IsSubscriptionActive mocks base method.
func (m *MockSubscriptionService) IsSubscriptionActive(ctx context.Context, shopID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSubscriptionActive", ctx, shopID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSubscriptionActive indicates an expected call of IsSubscriptionActive.
func (mr *MockSubscriptionServiceMockRecorder) IsSubscriptionActive(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSubscriptionActive", reflect.TypeOf((*MockSubscriptionService)(nil).IsSubscriptionActive), ctx, shopID)
}

// ExpireSubscriptions mocks base method.
func (m *MockSubscriptionService) ExpireSubscriptions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireSubscriptions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpireSubscriptions indicates an expected call of ExpireSubscriptions.
func (mr *MockSubscriptionServiceMockRecorder) ExpireSubscriptions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireSubscriptions", reflect.TypeOf((*MockSubscriptionService)(nil).ExpireSubscriptions), ctx)
}

// CancelSubscription mocks base method.
func (m *MockSubscriptionService) CancelSubscription(ctx context.Context, shopID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSubscription", ctx, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSubscription indicates an expected call of CancelSubscription.
func (mr *MockSubscriptionServiceMockRecorder) CancelSubscription(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSubscription", reflect.TypeOf((*MockSubscriptionService)(nil).CancelSubscription), ctx, shopID)
}
