// Code generated by MockGen. DO NOT EDIT.
// Source: service/system.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/zeirash/recapo/arion/common/response"
)

// MockSystemService is a mock of SystemService interface.
type MockSystemService struct {
	ctrl     *gomock.Controller
	recorder *MockSystemServiceMockRecorder
}

// MockSystemServiceMockRecorder is the mock recorder for MockSystemService.
type MockSystemServiceMockRecorder struct {
	mock *MockSystemService
}

// NewMockSystemService creates a new mock instance.
func NewMockSystemService(ctrl *gomock.Controller) *MockSystemService {
	mock := &MockSystemService{ctrl: ctrl}
	mock.recorder = &MockSystemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemService) EXPECT() *MockSystemServiceMockRecorder {
	return m.recorder
}

// GetSystemStats mocks base method.
func (m *MockSystemService) GetSystemStats(ctx context.Context) (*response.SystemStatsData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemStats", ctx)
	ret0, _ := ret[0].(*response.SystemStatsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemStats indicates an expected call of GetSystemStats.
func (mr *MockSystemServiceMockRecorder) GetSystemStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemStats", reflect.TypeOf((*MockSystemService)(nil).GetSystemStats), ctx)
}

// GetSystemShops mocks base method.
func (m *MockSystemService) GetSystemShops(ctx context.Context) ([]response.SystemShopData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemShops", ctx)
	ret0, _ := ret[0].([]response.SystemShopData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemShops indicates an expected call of GetSystemShops.
func (mr *MockSystemServiceMockRecorder) GetSystemShops(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemShops", reflect.TypeOf((*MockSystemService)(nil).GetSystemShops), ctx)
}

// GetSystemPayments mocks base method.
func (m *MockSystemService) GetSystemPayments(ctx context.Context) ([]response.SystemPaymentData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemPayments", ctx)
	ret0, _ := ret[0].([]response.SystemPaymentData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemPayments indicates an expected call of GetSystemPayments.
func (mr *MockSystemServiceMockRecorder) GetSystemPayments(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemPayments", reflect.TypeOf((*MockSystemService)(nil).GetSystemPayments), ctx)
}
