apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: recapo_master
    user: recapo_user
    secureJsonData:
      password: Recapo123!
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    isDefault: false
